Repository teja-paduri/Expense_Management, pull requests merged in 2022-04, with the labels that each got.

#69 Expensestorage
  controllers/expense_server.go
Labels: enhancement

#74 added category model
  models/payment.go
Labels: enhancement

#75 Populating With category wise expenditures
  Frontend/src/app/dashboard/Dashboard.jsx
Labels: enhancement

#82 Expenses API and testcases
  controllers/expense_management.db
  controllers/expense_server.go
  controllers/userserver_test.go
  models/expense.go
  routes/routes.go
Labels: enhancement

#93 modified the dashboard to send username to backend
  Frontend/src/app/dashboard/Dashboard.jsx
Labels: enhancement

#95 Expensestorage Retrival api update
  controllers/expense_server.go
  database/db.go
  models/expense.go
Labels: enhancement

#97 Testing/expense
  Frontend/cypress/integration/expense_spec.js
  Frontend/cypress/integration/login_spec.js
  Frontend/src/app/dashboard/Dashboard.jsx
  expense_management.db
Labels: Testing

#106 modified to display the username
  Frontend/src/app/dashboard/AppInlineProfile.jsx
Labels: enhancement

#116 Expensestorage
  models/income.go
  models/paymentsplit.go
Labels: enhancement

#117 Income and Payment split table: schema creation
  .DS_Store
  expense_management.db
  expense_management.sqbpro
Labels: enhancement

#120 Userpayments
  controllers/server.go
  controllers/userincome.go
  database/db.go
Labels: enhancement

#122 updated the routes for income and password udpation API
  routes/routes.go
Labels: enhancement

#130 Payment functionalities
  controllers/paymentsplit_server.go
  database/db.go
  expense_management.db
  expense_management.sqbpro
Labels: bug

#131 Userpayments
  database/db.go
  models/income.go
  models/paymentsplit.go
Labels: enhancement

#133 Payment functionalities : DELETE added
  database/db.go
  expense_management.db
  routes/routes.go
Labels: bug

#134 made minute changes in routes and db file and income update functiona…
  controllers/payment_server.go
  controllers/payment_test.go
  controllers/userincome.go
  database/db.go
  expense_management.db
  routes/routes.go
Labels: enhancement

#137 inserted delete user income functionality
  controllers/userincome.go
  database/db.go
Labels: enhancement

#141 Splitwise
  Frontend/src/app/Splitwise/Splitwise.jsx
  Frontend/src/app/expense/Expense.jsx
Labels: enhancement

#144 Userpayments
  controllers/server.go
  database/db.go
  routes/routes.go
Labels: enhancement

#146 modified the profile page
  Frontend/src/app/profile/Profile.jsx
Labels: enhancement

#147 updated a new endpoimt to implement update pwd
  Frontend/src/API.js
Labels: enhancement

#149 Userpayments
  controllers/paymentsplit_server.go
  database/db.go
  expense_management.db
  models/paymentsplit.go
Labels: enhancement

#150 Splitting borrowers and adding individual shares into DB
  controllers/paymentsplit_server.go
  database/db.go
  expense_management.db
Labels: enhancement

#151 updated user group expense functionality
  .DS_Store
  controllers/paymentsplit_server.go
  database/db.go
  expense_management.db
Labels: enhancement

#152 update pwd functionality
  Frontend/src/app/profile/Profile.jsx
Labels: enhancement

#153 profile component
  Frontend/src/app/profile/Profile.jsx
Labels: enhancement

#154 passing the userid to update pwd
  Frontend/src/app/profile/Profile.jsx
Labels: enhancement

#123 get all users api added
  controllers/server.go
  database/db.go
  routes/routes.go
Labels: bug

#157 Userpayments
  controllers/paymentsplit_server.go
  database/db.go
  expense_management.db
  routes/routes.go
Labels: enhancement

#167 updated backed unit test cases for user and expense server
  controllers/expense_server.go
  database/db.go
  expense_management.db
  tests/expenses_test.go
  tests/userserver_test.go
Labels: User Story, Testing

#172 Backend Documentation
  Sprint4/Backend Documentation.pdf
Labels: User Story
